export const mockFlights = [
    {
        id: 1,
        airline: "SkyWings",
        logo: "Plane", // reliable fallback for icon
        departureTime: "08:00",
        arrivalTime: "11:30",
        duration: "3h 30m",
        price: 350,
        stops: 0,
        origin: "JFK",
        destination: "LHR",
        aircraft: "Boeing 737 MAX",
    },
    {
        id: 2,
        airline: "Oceanic Air",
        logo: "Zap",
        departureTime: "14:00",
        arrivalTime: "22:00",
        duration: "8h 00m",
        price: 520,
        stops: 1,
        layovers: ["CDG"],
        origin: "JFK",
        destination: "LHR",
        aircraft: "Airbus A350",
    },
    {
        id: 3,
        airline: "Global Jet",
        logo: "Globe",
        departureTime: "06:00",
        arrivalTime: "09:30",
        duration: "3h 30m",
        price: 290,
        stops: 0,
        origin: "LAX",
        destination: "NRT",
        aircraft: "Boeing 787",
    },
];
